from __future__ import annotations

CATALOG: list[dict] = [
    {
        "id": "opencv-morphology",
        "name": "OpenCV Morphology",
        "family": "Classical CV",
        "task": "crack candidate segmentation",
        "backend": "OpenCV",
        "adapter": "morphology",
        "description": "Black-hat, thresholding and connected components for dark linear discontinuities.",
        "strengths": "Deterministic baseline, CPU-only, auditable and useful for crack morphology.",
        "requires_weights": False,
        "open_vocabulary": False,
    },
    {
        "id": "yolo11-det",
        "name": "YOLO11 Detection",
        "family": "YOLO",
        "task": "object detection",
        "backend": "Ultralytics",
        "adapter": "ultralytics-yolo",
        "description": "YOLO11 detector adapter for custom SHM checkpoints.",
        "strengths": "High-throughput UAV inspection and real-time inference.",
        "requires_weights": True,
        "open_vocabulary": False,
        "weights_env": "YOLO11_DET_WEIGHTS",
    },
    {
        "id": "yolo11-seg",
        "name": "YOLO11 Segmentation",
        "family": "YOLO",
        "task": "instance segmentation",
        "backend": "Ultralytics",
        "adapter": "ultralytics-yolo",
        "description": "YOLO11 instance segmentation with custom pathology weights.",
        "strengths": "Fast masks plus bounding boxes for defect area estimation.",
        "requires_weights": True,
        "open_vocabulary": False,
        "weights_env": "YOLO11_SEG_WEIGHTS",
    },
    {
        "id": "yolov8-det",
        "name": "YOLOv8 Detection",
        "family": "YOLO",
        "task": "object detection",
        "backend": "Ultralytics",
        "adapter": "ultralytics-yolo",
        "description": "YOLOv8 detector retained for comparison with published SHM pipelines.",
        "strengths": "Mature ecosystem and broad SHM literature footprint.",
        "requires_weights": True,
        "open_vocabulary": False,
        "weights_env": "YOLOV8_DET_WEIGHTS",
    },
    {
        "id": "yolov8-seg",
        "name": "YOLOv8 Segmentation",
        "family": "YOLO",
        "task": "instance segmentation",
        "backend": "Ultralytics",
        "adapter": "ultralytics-yolo",
        "description": "YOLOv8 segmentation adapter for legacy and comparative experiments.",
        "strengths": "Fast instance masks and easy export to ONNX/TensorRT.",
        "requires_weights": True,
        "open_vocabulary": False,
        "weights_env": "YOLOV8_SEG_WEIGHTS",
    },
    {
        "id": "rt-detr",
        "name": "RT-DETR",
        "family": "DETR",
        "task": "object detection",
        "backend": "Ultralytics",
        "adapter": "ultralytics-rtdetr",
        "description": "End-to-end real-time Detection Transformer with custom SHM checkpoint.",
        "strengths": "Strong global context and robust detection in visually complex scenes.",
        "requires_weights": True,
        "open_vocabulary": False,
        "weights_env": "RTDETR_WEIGHTS",
    },
    {
        "id": "yolo-world",
        "name": "YOLO-World",
        "family": "Open Vocabulary",
        "task": "zero-shot/open-vocabulary detection",
        "backend": "Ultralytics",
        "adapter": "ultralytics-world",
        "description": "Promptable detector using the shared SHM pathology vocabulary.",
        "strengths": "Rapid zero-shot screening before domain-specific fine-tuning.",
        "requires_weights": False,
        "open_vocabulary": True,
        "model_ref": "yolov8s-worldv2.pt",
    },
    {
        "id": "fastsam",
        "name": "FastSAM",
        "family": "Foundation Segmentation",
        "task": "class-agnostic segmentation",
        "backend": "Ultralytics",
        "adapter": "ultralytics-fastsam",
        "description": "Fast class-agnostic segmentation baseline.",
        "strengths": "Rapid geometric candidate extraction on large inspection images.",
        "requires_weights": False,
        "open_vocabulary": False,
        "model_ref": "FastSAM-s.pt",
    },
    {
        "id": "sam2",
        "name": "SAM 2.1",
        "family": "Foundation Segmentation",
        "task": "promptable/automatic segmentation",
        "backend": "Meta SAM2",
        "adapter": "sam2",
        "description": "Segment Anything 2 automatic mask generation for geometric candidate extraction.",
        "strengths": "Precise boundaries and reusable image/video segmentation foundation model.",
        "requires_weights": True,
        "open_vocabulary": False,
        "config_env": "SAM2_CONFIG",
        "weights_env": "SAM2_CHECKPOINT",
    },
    {
        "id": "grounding-dino",
        "name": "Grounding DINO",
        "family": "Open Vocabulary",
        "task": "zero-shot object detection",
        "backend": "Transformers",
        "adapter": "grounding-dino",
        "description": "Text-conditioned open-set detector with a common pathology prompt list.",
        "strengths": "No class-specific head required for initial screening.",
        "requires_weights": False,
        "open_vocabulary": True,
        "model_env": "GROUNDING_DINO_MODEL",
        "model_ref": "IDEA-Research/grounding-dino-tiny",
    },
    {
        "id": "grounded-sam2",
        "name": "Grounding DINO + SAM 2",
        "family": "Grounded Segmentation",
        "task": "open-vocabulary instance segmentation",
        "backend": "Transformers + Meta SAM2",
        "adapter": "grounded-sam2",
        "description": "Grounding DINO supplies pathology boxes and SAM 2 refines each box to a mask.",
        "strengths": "Semantic prompts combined with precise geometry.",
        "requires_weights": True,
        "open_vocabulary": True,
        "config_env": "SAM2_CONFIG",
        "weights_env": "SAM2_CHECKPOINT",
    },
    {
        "id": "detectron2-maskrcnn",
        "name": "Detectron2 Mask R-CNN",
        "family": "R-CNN",
        "task": "instance segmentation",
        "backend": "Detectron2",
        "adapter": "detectron2",
        "description": "Mask R-CNN adapter for pathology instance segmentation.",
        "strengths": "Stable laboratory baseline with precise masks and mature evaluation tooling.",
        "requires_weights": True,
        "open_vocabulary": False,
        "config_env": "DETECTRON2_CONFIG",
        "weights_env": "DETECTRON2_WEIGHTS",
    },
    {
        "id": "unet",
        "name": "U-Net",
        "family": "CNN Semantic Segmentation",
        "task": "semantic segmentation",
        "backend": "segmentation-models-pytorch",
        "adapter": "smp",
        "description": "U-Net with a configurable encoder and SHM checkpoint.",
        "strengths": "Strong baseline for thin cracks and dense pixel labeling.",
        "requires_weights": True,
        "open_vocabulary": False,
        "arch": "Unet",
        "weights_env": "UNET_WEIGHTS",
    },
    {
        "id": "unetplusplus",
        "name": "U-Net++",
        "family": "CNN Semantic Segmentation",
        "task": "semantic segmentation",
        "backend": "segmentation-models-pytorch",
        "adapter": "smp",
        "description": "Nested skip connections for multiscale damage segmentation.",
        "strengths": "Improved feature fusion for small and irregular defects.",
        "requires_weights": True,
        "open_vocabulary": False,
        "arch": "UnetPlusPlus",
        "weights_env": "UNETPP_WEIGHTS",
    },
    {
        "id": "deeplabv3plus",
        "name": "DeepLabV3+",
        "family": "CNN Semantic Segmentation",
        "task": "semantic segmentation",
        "backend": "segmentation-models-pytorch",
        "adapter": "smp",
        "description": "Atrous spatial pyramid pooling plus decoder for dense damage mapping.",
        "strengths": "Multiscale context with strong boundary recovery.",
        "requires_weights": True,
        "open_vocabulary": False,
        "arch": "DeepLabV3Plus",
        "weights_env": "DEEPLABV3PLUS_WEIGHTS",
    },
    {
        "id": "pspnet",
        "name": "PSPNet",
        "family": "CNN Semantic Segmentation",
        "task": "semantic segmentation",
        "backend": "segmentation-models-pytorch",
        "adapter": "smp",
        "description": "Pyramid scene parsing for context-aware pathology segmentation.",
        "strengths": "Useful when defect appearance depends on broader structural context.",
        "requires_weights": True,
        "open_vocabulary": False,
        "arch": "PSPNet",
        "weights_env": "PSPNET_WEIGHTS",
    },
    {
        "id": "fpn",
        "name": "FPN",
        "family": "CNN Semantic Segmentation",
        "task": "semantic segmentation",
        "backend": "segmentation-models-pytorch",
        "adapter": "smp",
        "description": "Feature Pyramid Network segmentation baseline.",
        "strengths": "Efficient multiscale representation for small and large defects.",
        "requires_weights": True,
        "open_vocabulary": False,
        "arch": "FPN",
        "weights_env": "FPN_WEIGHTS",
    },
    {
        "id": "pan",
        "name": "PAN",
        "family": "CNN Semantic Segmentation",
        "task": "semantic segmentation",
        "backend": "segmentation-models-pytorch",
        "adapter": "smp",
        "description": "Pyramid Attention Network segmentation adapter.",
        "strengths": "Attention-guided multiscale feature aggregation.",
        "requires_weights": True,
        "open_vocabulary": False,
        "arch": "PAN",
        "weights_env": "PAN_WEIGHTS",
    },
    {
        "id": "manet",
        "name": "MAnet",
        "family": "CNN Semantic Segmentation",
        "task": "semantic segmentation",
        "backend": "segmentation-models-pytorch",
        "adapter": "smp",
        "description": "Multi-scale attention segmentation model.",
        "strengths": "Attention to irregular damage regions and fine local patterns.",
        "requires_weights": True,
        "open_vocabulary": False,
        "arch": "MAnet",
        "weights_env": "MANET_WEIGHTS",
    },
    {
        "id": "linknet",
        "name": "LinkNet",
        "family": "CNN Semantic Segmentation",
        "task": "semantic segmentation",
        "backend": "segmentation-models-pytorch",
        "adapter": "smp",
        "description": "Efficient encoder-decoder segmentation baseline.",
        "strengths": "Lower inference cost for field deployment.",
        "requires_weights": True,
        "open_vocabulary": False,
        "arch": "Linknet",
        "weights_env": "LINKNET_WEIGHTS",
    },
    {
        "id": "segnet",
        "name": "SegNet",
        "family": "CNN Semantic Segmentation",
        "task": "semantic segmentation",
        "backend": "MMSegmentation",
        "adapter": "mmseg",
        "description": "SegNet integration through MMSeg config/checkpoint.",
        "strengths": "Established encoder-decoder reference for pixel-level crack studies.",
        "requires_weights": True,
        "open_vocabulary": False,
        "config_env": "MMSEG_SEGNET_CONFIG",
        "weights_env": "MMSEG_SEGNET_WEIGHTS",
    },
    {
        "id": "segformer",
        "name": "SegFormer",
        "family": "Transformer Segmentation",
        "task": "semantic segmentation",
        "backend": "Transformers",
        "adapter": "hf-segmentation",
        "description": "Hierarchical transformer encoder with lightweight decoder.",
        "strengths": "Efficient global/local context for complex damage texture.",
        "requires_weights": True,
        "open_vocabulary": False,
        "model_env": "SEGFORMER_MODEL",
    },
    {
        "id": "mask2former",
        "name": "Mask2Former",
        "family": "Transformer Segmentation",
        "task": "semantic/instance segmentation",
        "backend": "Transformers",
        "adapter": "hf-segmentation",
        "description": "Universal masked-attention segmentation architecture.",
        "strengths": "Unified semantic, instance and panoptic segmentation formulation.",
        "requires_weights": True,
        "open_vocabulary": False,
        "model_env": "MASK2FORMER_MODEL",
    },
    {
        "id": "hrnet-ocr",
        "name": "HRNet + OCR",
        "family": "High-Resolution Segmentation",
        "task": "semantic segmentation",
        "backend": "MMSegmentation",
        "adapter": "mmseg",
        "description": "High-resolution feature preservation with object-context reasoning.",
        "strengths": "Fine boundary retention for thin cracks and exposed rebar.",
        "requires_weights": True,
        "open_vocabulary": False,
        "config_env": "MMSEG_HRNET_CONFIG",
        "weights_env": "MMSEG_HRNET_WEIGHTS",
    },
    {
        "id": "upernet-swin",
        "name": "UPerNet + Swin",
        "family": "Transformer Segmentation",
        "task": "semantic segmentation",
        "backend": "MMSegmentation",
        "adapter": "mmseg",
        "description": "Swin Transformer backbone with UPerNet decoder.",
        "strengths": "Multiscale transformer context for broad structural scenes.",
        "requires_weights": True,
        "open_vocabulary": False,
        "config_env": "MMSEG_UPERNET_CONFIG",
        "weights_env": "MMSEG_UPERNET_WEIGHTS",
    },
    {
        "id": "crackformer",
        "name": "CrackFormer",
        "family": "Crack-specific Transformer",
        "task": "crack segmentation",
        "backend": "MMSeg/ONNX",
        "adapter": "mmseg",
        "description": "Adapter slot for CrackFormer-compatible config/checkpoint.",
        "strengths": "Specialized thin-crack segmentation architecture.",
        "requires_weights": True,
        "open_vocabulary": False,
        "config_env": "MMSEG_CRACKFORMER_CONFIG",
        "weights_env": "MMSEG_CRACKFORMER_WEIGHTS",
    },
    {
        "id": "crackformer-ii",
        "name": "CrackFormer-II",
        "family": "Crack-specific Transformer",
        "task": "crack segmentation",
        "backend": "MMSeg/ONNX",
        "adapter": "mmseg",
        "description": "Adapter slot for CrackFormer-II-compatible config/checkpoint.",
        "strengths": "Dedicated crack representation for challenging backgrounds.",
        "requires_weights": True,
        "open_vocabulary": False,
        "config_env": "MMSEG_CRACKFORMER2_CONFIG",
        "weights_env": "MMSEG_CRACKFORMER2_WEIGHTS",
    },
    {
        "id": "dinov2-seg",
        "name": "DINOv2 Segmentation Head",
        "family": "Self-Supervised ViT",
        "task": "semantic segmentation",
        "backend": "Transformers",
        "adapter": "hf-segmentation",
        "description": "DINOv2 features with a pathology segmentation head supplied as a local/HF model.",
        "strengths": "Strong transferable visual representations under limited labeled data.",
        "requires_weights": True,
        "open_vocabulary": False,
        "model_env": "DINOV2_SEG_MODEL",
    },
    {
        "id": "onnx-custom",
        "name": "Custom ONNX",
        "family": "Portable Runtime",
        "task": "semantic segmentation",
        "backend": "ONNX Runtime",
        "adapter": "onnx",
        "description": "Generic NCHW segmentation adapter for exported SHM research models.",
        "strengths": "Framework-neutral deployment and reproducible inference.",
        "requires_weights": True,
        "open_vocabulary": False,
        "weights_env": "ONNX_CUSTOM_MODEL",
    },
]
