import React,{useEffect,useMemo,useState}from"react";
import{Upload,Play,CheckCircle2,AlertTriangle,Clock3,Layers3,Server,Save,Wifi,WifiOff,FlaskConical,ExternalLink,HardDrive}from"lucide-react";
const BUILD_API=(import.meta.env.VITE_API_URL||"https://shm-api-production-01f8.up.railway.app").replace(/\/$/,"");
const txt={ok:"Concluído",missing_dependency:"Dependência ausente",missing_weights:"Pesos ausentes",error:"Erro",skipped:"Registrado"};
function initialApi(){const q=new URLSearchParams(location.search).get("api");let stored=localStorage.getItem("shmApiUrl");const obsolete="https://shm-api-production.up.railway.app";if(stored===obsolete){stored=BUILD_API;localStorage.setItem("shmApiUrl",BUILD_API)}const v=(q||stored||BUILD_API||"").replace(/\/$/,"");if(q){localStorage.setItem("shmApiUrl",v);history.replaceState({},document.title,location.pathname)}return v}
function modeLabel(e){if(e.domain_mode==="public_shm_checkpoint")return"Checkpoint SHM público";if(e.domain_mode==="zero_shot")return"Zero-shot SHM";if(e.domain_mode==="classical")return"Baseline clássico";if(e.domain_mode==="shm_checkpoint")return"Checkpoint SHM local";if(e.domain_mode==="generic_pretrained")return"Pré-treinado genérico";return e.domain_mode||"Genérico"}
function Card({r}){return <article className="card"><div className="head"><div><h3>{r.name}</h3><span className={"badge "+r.status}>{txt[r.status]||r.status}</span></div><span className="lat"><Clock3 size={14}/>{r.latency_ms.toFixed(0)} ms</span></div>{r.overlay_png_base64?<img src={"data:image/png;base64,"+r.overlay_png_base64}/>:<div className="empty">{r.message||"Sem visualização"}</div>}<div className="metrics"><b>{r.detections.length}</b> achados {Object.entries(r.metrics||{}).slice(0,6).map(([k,v])=><span key={k}>{k}: {String(v)}</span>)}</div>{r.message&&<p className="msg">{r.message}</p>}</article>}
export default function App(){const[api,setApi]=useState(initialApi),[apiDraft,setApiDraft]=useState(initialApi),[online,setOnline]=useState(false),[storage,setStorage]=useState(null),[warmup,setWarmup]=useState(null);const[eng,setEng]=useState([]),[sel,setSel]=useState(new Set()),[file,setFile]=useState(null),[prev,setPrev]=useState(null),[res,setRes]=useState(null),[busy,setBusy]=useState(false),[progress,setProgress]=useState(null),[err,setErr]=useState("");
async function loadEngines(base=api){setErr("");setOnline(false);if(!base){setEng([]);setSel(new Set());return}try{const [hr,er,sr,wr]=await Promise.all([fetch(base+"/health",{signal:AbortSignal.timeout(12000)}),fetch(base+"/engines",{signal:AbortSignal.timeout(20000)}),fetch(base+"/storage",{signal:AbortSignal.timeout(12000)}),fetch(base+"/warmup-status",{signal:AbortSignal.timeout(12000)})]);if(!hr.ok)throw new Error("Backend respondeu "+hr.status);if(!er.ok)throw new Error(await er.text());const x=await er.json();setEng(x);setSel(new Set(x.filter(e=>e.ready&&e.recommended).map(e=>e.id)));if(sr.ok)setStorage(await sr.json());if(wr.ok)setWarmup(await wr.json());setOnline(true)}catch(e){setEng([]);setSel(new Set());setErr("Backend indisponível: "+String(e))}}
useEffect(()=>{loadEngines(api)},[api]);useEffect(()=>()=>{if(prev)URL.revokeObjectURL(prev)},[prev]);const ready=useMemo(()=>eng.filter(e=>e.ready).length,[eng]);const recommended=useMemo(()=>eng.filter(e=>e.ready&&e.recommended).length,[eng]);function saveApi(){const v=apiDraft.trim().replace(/\/$/,"");localStorage.setItem("shmApiUrl",v);setApi(v)}function pick(f){setFile(f);setRes(null);setProgress(null);if(prev)URL.revokeObjectURL(prev);setPrev(f?URL.createObjectURL(f):null)}function toggle(id){setSel(s=>{let n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n})}function selectReady(){setSel(new Set(eng.filter(e=>e.ready).map(e=>e.id)))}function selectRecommended(){setSel(new Set(eng.filter(e=>e.ready&&e.recommended).map(e=>e.id)))}
async function run(){if(!file||!api)return;setBusy(true);setErr("");setRes(null);setProgress({state:"queued",completed:0,total:sel.size,current_engine:null});let fd=new FormData();fd.append("file",file);fd.append("engines",[...sel].join(","));
try{
  let start=await fetch(api+"/jobs/compare",{method:"POST",body:fd});
  if(start.status===404||start.status===405){
    let legacy=await fetch(api+"/compare",{method:"POST",body:fd});if(!legacy.ok)throw new Error(await legacy.text());setRes(await legacy.json());return;
  }
  if(!start.ok)throw new Error(await start.text());
  const j=await start.json();let attempts=0;
  while(attempts<1200){
    await new Promise(r=>setTimeout(r,750));attempts++;
    let poll=await fetch(api+"/jobs/"+j.job_id,{signal:AbortSignal.timeout(12000)});
    if(!poll.ok)throw new Error(await poll.text());
    let st=await poll.json();setProgress({state:st.state,completed:st.completed,total:st.total,current_engine:st.current_engine});
    if(st.state==="done"){setRes(st.result);break}
    if(st.state==="error")throw new Error(st.error||"Falha no processamento");
  }
  if(attempts>=1200&&!res)throw new Error("Tempo limite excedido para a comparação.")
  fetch(api+"/storage").then(x=>x.ok?x.json():null).then(x=>x&&setStorage(x)).catch(()=>{});
}catch(e){setErr(String(e))}finally{setBusy(false)}}
return <main><header><div><div className="eye"><Layers3 size={16}/> SHM · OAEs · COMPUTER VISION</div><h1>SHM Vision Lab</h1><p>Uma imagem. Vários motores. Resultados normalizados lado a lado.</p></div><div className="sum"><b>{eng.length}</b><span>motores</span><b>{ready}</b><span>prontos</span><b>{recommended}</b><span>recomendados agora</span></div></header>
<section className="apiBar"><div className="apiTitle"><Server size={18}/><div><b>Backend de inferência</b><span>{online?<><Wifi size={13}/> Online</>:<><WifiOff size={13}/> Não conectado</>}</span></div></div><input value={apiDraft} onChange={e=>setApiDraft(e.target.value)} placeholder="https://seu-backend.up.railway.app"/><button onClick={saveApi}><Save size={16}/> Conectar</button></section>
{storage&&<div className="storageBar"><HardDrive size={15}/><span>Cache de modelos: <b>{storage.used_mb} MB usados</b> · {storage.free_mb} MB livres · volume {storage.total_mb} MB</span>{warmup&&<span className={"warmupState "+warmup.state}>Warmup: {warmup.state} · {Object.values(warmup.engines||{}).filter(x=>x.status==="ok").length} motores verificados</span>}</div>}
<div className="scienceNote"><FlaskConical size={17}/><span><b>Perfil cloud compacto:</b> prioriza checkpoints públicos realmente treinados para patologia estrutural. Modelos genéricos e foundation pesados permanecem registrados, mas ficam desativados por padrão para evitar resultados sem validade de domínio e estouro de memória/armazenamento.</span></div>
<section className="work"><div className="left"><label className="drop"><input type="file" accept="image/*" onChange={e=>pick(e.target.files?.[0])}/>{prev?<img src={prev}/>:<><Upload size={34}/><b>Selecionar imagem da inspeção</b><span>JPG, PNG ou WEBP</span></>}</label><button className="run" disabled={!file||busy||!sel.size||!online} onClick={run}><Play size={18}/>{busy&&progress?`Processando ${progress.completed}/${progress.total}...`:"Executar comparação"}</button>{busy&&progress&&<div className="jobProgress"><div className="jobProgressTop"><span>{progress.current_engine?`Motor: ${eng.find(e=>e.id===progress.current_engine)?.name||progress.current_engine}`:"Preparando fila de inferência..."}</span><b>{progress.completed}/{progress.total}</b></div><div className="jobTrack"><i style={{width:`${progress.total?Math.round(progress.completed/progress.total*100):0}%`}}/></div></div>}{err&&<div className="error">{err}</div>}</div><div className="panel"><div className="pt"><h2>Motores</h2><div className="selectBtns"><button onClick={selectRecommended}>Recomendados</button><button onClick={selectReady}>Prontos</button></div></div><div className="elist">{eng.length?eng.map(e=><label className={"engine "+(!e.ready?"disabled":"")} key={e.id}><input type="checkbox" disabled={!e.ready} checked={sel.has(e.id)} onChange={()=>toggle(e.id)}/><div><b>{e.name}{e.recommended&&<em> recomendado</em>}{warmup?.engines?.[e.id]?.status==="ok"&&<em className="verified"> verificado online</em>}</b><span>{e.family} · {e.task.replaceAll("_"," ")} · {modeLabel(e)}</span><small>{e.description}</small>{e.license&&<small className="license">Licença: {e.license}{e.source_url&&<> · <a href={e.source_url} target="_blank" rel="noreferrer" onClick={ev=>ev.stopPropagation()}>fonte <ExternalLink size={10}/></a></>}</small>}{!e.ready&&e.reason&&<small className="reason">{e.reason}</small>}</div>{e.ready?<CheckCircle2 className="ok" size={18}/>:<AlertTriangle className="warn" size={18}/>}</label>):<div className="engineEmpty">Conecte o backend online para carregar os motores.</div>}</div></div></section>
{res&&<section className="results"><h2>Comparação</h2><p>{res.image_width} × {res.image_height}px · mesma entrada para todos os motores selecionados</p>
{Object.keys(res.consensus||{}).length>0&&<div className="consensus"><div className="consensusHead"><b>Concordância entre motores</b><span>Concordância não equivale a verdade-terreno; indica apenas quantos motores sinalizaram a mesma categoria normalizada.</span></div><div className="consensusGrid">{Object.entries(res.consensus).map(([key,c])=><div className="consensusItem" key={key}><strong>{c.label}</strong><span>{c.engine_count}/{c.successful_engine_count} motores · {(c.agreement_ratio*100).toFixed(0)}%</span><small>{c.detections} achados{c.mean_score!=null?` · confiança média ${(c.mean_score*100).toFixed(0)}%`:""}</small></div>)}</div></div>}
{res.consensus_overlay_png_base64&&<div className="ensembleView"><div><b>Mapa espacial de consenso</b><span>Caixas agrupadas por categoria e sobreposição espacial (IoU); a espessura aumenta com o número de motores concordantes.</span></div><img src={"data:image/png;base64,"+res.consensus_overlay_png_base64}/>{res.spatial_consensus?.length>0&&<div className="clusterChips">{res.spatial_consensus.slice(0,12).map(c=><span key={c.id}>{c.label}: {c.engine_count}/{c.successful_engine_count} · IoU≥{c.iou_threshold}</span>)}</div>}</div>}<div className="compareTable"><div className="compareRow compareHeader"><span>Motor</span><span>Estado</span><span>Achados</span><span>Latência</span></div>{[...res.results].sort((a,b)=>a.latency_ms-b.latency_ms).map(r=><div className="compareRow" key={r.engine_id}><span>{r.name}</span><span>{txt[r.status]||r.status}</span><span>{r.detections.length}</span><span>{r.latency_ms.toFixed(0)} ms</span></div>)}</div>
<div className="grid">{res.results.map(r=><Card key={r.engine_id} r={r}/>)}</div></section>}</main>}
